awk '
/const RiskDoughnut: React\.FC</ {
  in_risk = 1
  print "const RiskDoughnut: React.FC<{"
  print "  normal: number;"
  print "  risk: number;"
  print "  danger: number;"
  print "  title: string;"
  print "}> = ({ normal, risk, danger, title }) => {"
  print "  const total = normal + risk + danger;"
  print "  "
  print "  const pctNormal = total > 0 ? Math.round((normal / total) * 100) : 0;"
  print "  const pctRisk = total > 0 ? Math.round((risk / total) * 100) : 0;"
  print "  const pctDanger = total > 0 ? Math.round((danger / total) * 100) : 0;"
  print ""
  print "  // SVG parameters"
  print "  const size = 160;"
  print "  const strokeWidth = 14;"
  print "  const center = size / 2;"
  print "  const radius = (size - strokeWidth) / 2;"
  print "  const circumference = 2 * Math.PI * radius;"
  print ""
  print "  // Segments calculation"
  print "  const offsetNormal = circumference;"
  print "  const offsetRisk = offsetNormal - (circumference * pctNormal) / 100;"
  print "  const offsetDanger = offsetRisk - (circumference * pctRisk) / 100;"
  print ""
  print "  return ("
  print "    <div className=\"bg-white p-5 rounded-2xl border border-slate-200 shadow-xs flex flex-col items-center\">"
  print "      <h4 className=\"text-[10px] font-bold text-slate-500 uppercase tracking-wider text-center mb-4\">{title}</h4>"
  print "      "
  print "      {total === 0 ? ("
  print "        <div className=\"h-[160px] flex flex-col items-center justify-center text-slate-400 text-xs text-center space-y-1\">"
  print "          <EyeOff className=\"w-8 h-8 text-slate-300\" />"
  print "          <p>ไม่มีข้อมูลแสดงผล</p>"
  print "        </div>"
  print "      ) : ("
  print "        <div className=\"flex flex-col sm:flex-row items-center gap-6 w-full justify-center\">"
  print "          "
  print "          {/* Circular SVG Chart */}"
  print "          <div className=\"relative w-[160px] h-[160px] shrink-0\">"
  print "            <svg width={size} height={size} className=\"transform -rotate-90\">"
  print "              {/* Background circle */}"
  print "              <circle"
  print "                cx={center}"
  print "                cy={center}"
  print "                r={radius}"
  print "                fill=\"transparent\""
  print "                stroke=\"#f1f5f9\""
  print "                strokeWidth={strokeWidth}"
  print "              />"
  print "              "
  print "              {/* Normal Segment (White/Greenish) */}"
  print "              {pctNormal > 0 && ("
  print "                <circle"
  print "                  cx={center}"
  print "                  cy={center}"
  print "                  r={radius}"
  print "                  fill=\"transparent\""
  print "                  stroke=\"#10b981\" // emerald-500"
  print "                  strokeWidth={strokeWidth}"
  print "                  strokeDasharray={circumference}"
  print "                  strokeDashoffset={circumference - (circumference * pctNormal) / 100}"
  print "                />"
  print "              )}"
  print "              {/* Risk Segment */}"
  print "              {pctRisk > 0 && ("
  print "                <circle"
  print "                  cx={center}"
  print "                  cy={center}"
  print "                  r={radius}"
  print "                  fill=\"transparent\""
  print "                  stroke=\"#f59e0b\" // amber-500"
  print "                  strokeWidth={strokeWidth}"
  print "                  strokeDasharray={circumference}"
  print "                  strokeDashoffset={circumference - (circumference * pctRisk) / 100}"
  print "                  style={{ transform: `rotate(${pctNormal * 3.6}deg)`, transformOrigin: \"center\" }}"
  print "                />"
  print "              )}"
  print "              {/* Danger Segment */}"
  print "              {pctDanger > 0 && ("
  print "                <circle"
  print "                  cx={center}"
  print "                  cy={center}"
  print "                  r={radius}"
  print "                  fill=\"transparent\""
  print "                  stroke=\"#ef4444\" // red-500"
  print "                  strokeWidth={strokeWidth}"
  print "                  strokeDasharray={circumference}"
  print "                  strokeDashoffset={circumference - (circumference * pctDanger) / 100}"
  print "                  style={{ transform: `rotate(${(pctNormal + pctRisk) * 3.6}deg)`, transformOrigin: \"center\" }}"
  print "                />"
  print "              )}"
  print "            </svg>"
  print "            {/* Inner Content */}"
  print "            <div className=\"absolute inset-0 flex flex-col items-center justify-center\">"
  print "              <span className=\"text-2xl font-black text-slate-800\">{total}</span>"
  print "              <span className=\"text-[10px] text-slate-400 font-bold uppercase tracking-wider\">เคสทั้งหมด</span>"
  print "            </div>"
  print "          </div>"
  print ""
  print "          {/* Legend Table */}"
  print "          <div className=\"space-y-3 w-full max-w-[140px]\">"
  print "            <div className=\"flex justify-between items-start text-xs\">"
  print "              <div className=\"flex items-center gap-1.5\">"
  print "                <span className=\"w-2.5 h-2.5 bg-emerald-500 rounded-full\" />"
  print "                <span className=\"text-slate-600 font-medium whitespace-nowrap\">ปกติ</span>"
  print "              </div>"
  print "              <div className=\"flex flex-col items-end\">"
  print "                <span className=\"font-bold text-slate-800 whitespace-nowrap\">{normal} ราย</span>"
  print "                <span className=\"text-[10px] font-semibold text-slate-500\">({pctNormal}%)</span>"
  print "              </div>"
  print "            </div>"
  print "            "
  print "            <div className=\"flex justify-between items-start text-xs\">"
  print "              <div className=\"flex items-center gap-1.5\">"
  print "                <span className=\"w-2.5 h-2.5 bg-amber-500 rounded-full\" />"
  print "                <span className=\"text-slate-600 font-medium whitespace-nowrap\">กลุ่มเสี่ยง</span>"
  print "              </div>"
  print "              <div className=\"flex flex-col items-end\">"
  print "                <span className=\"font-bold text-slate-800 whitespace-nowrap\">{risk} ราย</span>"
  print "                <span className=\"text-[10px] font-semibold text-slate-500\">({pctRisk}%)</span>"
  print "              </div>"
  print "            </div>"
  print ""
  print "            <div className=\"flex justify-between items-start text-xs\">"
  print "              <div className=\"flex items-center gap-1.5\">"
  print "                <span className=\"w-2.5 h-2.5 bg-red-500 rounded-full\" />"
  print "                <span className=\"text-slate-600 font-medium whitespace-nowrap\">สงสัยป่วย</span>"
  print "              </div>"
  print "              <div className=\"flex flex-col items-end\">"
  print "                <span className=\"font-bold text-slate-800 whitespace-nowrap\">{danger} ราย</span>"
  print "                <span className=\"text-[10px] font-semibold text-slate-500\">({pctDanger}%)</span>"
  print "              </div>"
  print "            </div>"
  print "          </div>"
  print "        </div>"
  print "      )}"
  print "    </div>"
  print "  );"
  print "};"
  next
}
in_risk && /const LifestyleBehaviors3O2S: React\.FC</ {
  in_risk = 0
  print $0
  next
}
in_risk {
  next
}
1
' src/components/NcdDashboard.tsx > src/components/NcdDashboard.tsx.tmp && mv src/components/NcdDashboard.tsx.tmp src/components/NcdDashboard.tsx
