awk '
NR < 21 { print $0; next }
NR == 21 {
  print "// Reusable custom circular progress gauge"
  print "const BMIDoughnut: React.FC<{"
  print "  underweight: number;"
  print "  normal: number;"
  print "  overweight: number;"
  print "  obese1: number;"
  print "  obese2: number;"
  print "  title: string;"
  print "}> = ({ underweight, normal, overweight, obese1, obese2, title }) => {"
  print "  const total = underweight + normal + overweight + obese1 + obese2;"
  print "  const pctUW = total > 0 ? (underweight / total) * 100 : 0;"
  print "  const pctN = total > 0 ? (normal / total) * 100 : 0;"
  print "  const pctOW = total > 0 ? (overweight / total) * 100 : 0;"
  print "  const pctOB1 = total > 0 ? (obese1 / total) * 100 : 0;"
  print "  const pctOB2 = total > 0 ? (obese2 / total) * 100 : 0;"
  print "  const size = 160;"
  print "  const strokeWidth = 14;"
  print "  const center = size / 2;"
  print "  const radius = (size - strokeWidth) / 2;"
  print "  const circumference = 2 * Math.PI * radius;"
  print "  const dasharray = circumference;"
  print "  return ("
  print "    <div className=\"bg-white p-5 rounded-2xl border border-slate-200 shadow-xs flex flex-col items-center\">"
  print "      <h4 className=\"text-[10px] font-bold text-slate-500 uppercase tracking-wider text-center mb-4\">{title}</h4>"
  print "      {total === 0 ? ("
  print "        <div className=\"h-[160px] flex flex-col items-center justify-center text-slate-400 text-xs text-center space-y-1\">"
  print "          <EyeOff className=\"w-8 h-8 text-slate-300\" />"
  print "          <p>ไม่มีข้อมูลแสดงผล</p>"
  print "        </div>"
  print "      ) : ("
  print "        <div className=\"flex flex-col sm:flex-row items-center gap-6 w-full justify-center\">"
  print "          <div className=\"relative w-[160px] h-[160px] shrink-0\">"
  print "            <svg width={size} height={size} className=\"-rotate-90 transform\">"
  print "              <circle cx={center} cy={center} r={radius} fill=\"transparent\" stroke=\"#f1f5f9\" strokeWidth={strokeWidth} />"
  print "              {pctUW > 0 && <circle cx={center} cy={center} r={radius} fill=\"transparent\" stroke=\"#3b82f6\" strokeWidth={strokeWidth} strokeDasharray={dasharray} strokeDashoffset={circumference - (circumference * pctUW) / 100} />}"
  print "              {pctN > 0 && <circle cx={center} cy={center} r={radius} fill=\"transparent\" stroke=\"#10b981\" strokeWidth={strokeWidth} strokeDasharray={dasharray} strokeDashoffset={circumference - (circumference * pctN) / 100} style={{ transform: `rotate(${pctUW * 3.6}deg)`, transformOrigin: \"center\" }} />}"
  print "              {pctOW > 0 && <circle cx={center} cy={center} r={radius} fill=\"transparent\" stroke=\"#f59e0b\" strokeWidth={strokeWidth} strokeDasharray={dasharray} strokeDashoffset={circumference - (circumference * pctOW) / 100} style={{ transform: `rotate(${(pctUW + pctN) * 3.6}deg)`, transformOrigin: \"center\" }} />}"
  print "              {pctOB1 > 0 && <circle cx={center} cy={center} r={radius} fill=\"transparent\" stroke=\"#f43f5e\" strokeWidth={strokeWidth} strokeDasharray={dasharray} strokeDashoffset={circumference - (circumference * pctOB1) / 100} style={{ transform: `rotate(${(pctUW + pctN + pctOW) * 3.6}deg)`, transformOrigin: \"center\" }} />}"
  print "              {pctOB2 > 0 && <circle cx={center} cy={center} r={radius} fill=\"transparent\" stroke=\"#8b5cf6\" strokeWidth={strokeWidth} strokeDasharray={dasharray} strokeDashoffset={circumference - (circumference * pctOB2) / 100} style={{ transform: `rotate(${(pctUW + pctN + pctOW + pctOB1) * 3.6}deg)`, transformOrigin: \"center\" }} />}"
  print "            </svg>"
  print "            <div className=\"absolute inset-0 flex flex-col items-center justify-center\">"
  print "              <span className=\"text-2xl font-black text-slate-800\">{total}</span>"
  print "              <span className=\"text-[10px] text-slate-400 font-bold uppercase tracking-wider\">เคสทั้งหมด</span>"
  print "            </div>"
  print "          </div>"
  print "          <div className=\"space-y-3 w-full max-w-[140px]\">"
  print "            <div className=\"flex justify-between items-start text-xs\">"
  print "              <div className=\"flex items-center gap-1.5\">"
  print "                <span className=\"w-2.5 h-2.5 bg-blue-500 rounded-full\" />"
  print "                <span className=\"text-slate-600 font-medium whitespace-nowrap\">ผอม</span>"
  print "              </div>"
  print "              <div className=\"flex flex-col items-end\">"
  print "                <span className=\"font-bold text-slate-800 whitespace-nowrap\">{underweight} ราย</span>"
  print "                <span className=\"text-[10px] font-semibold text-slate-500\">({Math.round(pctUW)}%)</span>"
  print "              </div>"
  print "            </div>"
  print "            <div className=\"flex justify-between items-start text-xs\">"
  print "              <div className=\"flex items-center gap-1.5\">"
  print "                <span className=\"w-2.5 h-2.5 bg-emerald-500 rounded-full\" />"
  print "                <span className=\"text-slate-600 font-medium whitespace-nowrap\">ปกติ</span>"
  print "              </div>"
  print "              <div className=\"flex flex-col items-end\">"
  print "                <span className=\"font-bold text-slate-800 whitespace-nowrap\">{normal} ราย</span>"
  print "                <span className=\"text-[10px] font-semibold text-slate-500\">({Math.round(pctN)}%)</span>"
  print "              </div>"
  print "            </div>"
  print "            <div className=\"flex justify-between items-start text-xs\">"
  print "              <div className=\"flex items-center gap-1.5\">"
  print "                <span className=\"w-2.5 h-2.5 bg-amber-500 rounded-full\" />"
  print "                <span className=\"text-slate-600 font-medium whitespace-nowrap\">ท้วม</span>"
  print "              </div>"
  print "              <div className=\"flex flex-col items-end\">"
  print "                <span className=\"font-bold text-slate-800 whitespace-nowrap\">{overweight} ราย</span>"
  print "                <span className=\"text-[10px] font-semibold text-slate-500\">({Math.round(pctOW)}%)</span>"
  print "              </div>"
  print "            </div>"
  print "            <div className=\"flex justify-between items-start text-xs\">"
  print "              <div className=\"flex items-center gap-1.5\">"
  print "                <span className=\"w-2.5 h-2.5 bg-rose-500 rounded-full\" />"
  print "                <span className=\"text-slate-600 font-medium whitespace-nowrap\">อ้วน</span>"
  print "              </div>"
  print "              <div className=\"flex flex-col items-end\">"
  print "                <span className=\"font-bold text-slate-800 whitespace-nowrap\">{obese1} ราย</span>"
  print "                <span className=\"text-[10px] font-semibold text-slate-500\">({Math.round(pctOB1)}%)</span>"
  print "              </div>"
  print "            </div>"
  print "            <div className=\"flex justify-between items-start text-xs\">"
  print "              <div className=\"flex items-center gap-1.5\">"
  print "                <span className=\"w-2.5 h-2.5 bg-purple-500 rounded-full\" />"
  print "                <span className=\"text-slate-600 font-medium whitespace-nowrap\">อ้วนมาก</span>"
  print "              </div>"
  print "              <div className=\"flex flex-col items-end\">"
  print "                <span className=\"font-bold text-slate-800 whitespace-nowrap\">{obese2} ราย</span>"
  print "                <span className=\"text-[10px] font-semibold text-slate-500\">({Math.round(pctOB2)}%)</span>"
  print "              </div>"
  print "            </div>"
  print "          </div>"
  print "        </div>"
  print "      )}"
  print "    </div>"
  print "  );"
  print "};"
  next
}
NR > 21 && NR < 140 { next }
NR >= 140 { print $0 }
' src/components/NcdDashboard.tsx > src/components/NcdDashboard.tsx.tmp && mv src/components/NcdDashboard.tsx.tmp src/components/NcdDashboard.tsx
