awk '
/const RiskDoughnut: React.FC/ {
  print "const BMIDoughnut: React.FC<{"
  print "  underweight: number;"
  print "  normal: number;"
  print "  overweight: number;"
  print "  obese1: number;"
  print "  obese2: number;"
  print "  title: string;"
  print "}> = ({ underweight, normal, overweight, obese1, obese2, title }) => {"
  print "  const total = underweight + normal + overweight + obese1 + obese2;"
  print ""
  print "  const pctUW = total > 0 ? (underweight / total) * 100 : 0;"
  print "  const pctN = total > 0 ? (normal / total) * 100 : 0;"
  print "  const pctOW = total > 0 ? (overweight / total) * 100 : 0;"
  print "  const pctOB1 = total > 0 ? (obese1 / total) * 100 : 0;"
  print "  const pctOB2 = total > 0 ? (obese2 / total) * 100 : 0;"
  print ""
  print "  const size = 160;"
  print "  const strokeWidth = 14;"
  print "  const center = size / 2;"
  print "  const radius = (size - strokeWidth) / 2;"
  print "  const circumference = 2 * Math.PI * radius;"
  print ""
  print "  const dasharray = circumference;"
  print "  const offsetUW = circumference;"
  print "  const offsetN = offsetUW - (pctUW / 100) * circumference;"
  print "  const offsetOW = offsetN - (pctN / 100) * circumference;"
  print "  const offsetOB1 = offsetOW - (pctOW / 100) * circumference;"
  print "  const offsetOB2 = offsetOB1 - (pctOB1 / 100) * circumference;"
  print ""
  print "  return ("
  print "    <div className=\"bg-white rounded-2xl p-5 border border-slate-200 shadow-sm flex flex-col items-center justify-between\">"
  print "      <h3 className=\"text-sm font-black text-slate-800 text-center uppercase tracking-wider mb-2\">{title}</h3>"
  print "      <div className=\"relative w-40 h-40\">"
  print "        <svg width={size} height={size} className=\"-rotate-90 transform\">"
  print "          <circle cx={center} cy={center} r={radius} fill=\"transparent\" stroke=\"#f1f5f9\" strokeWidth={strokeWidth} />"
  print "          <circle cx={center} cy={center} r={radius} fill=\"transparent\" stroke=\"#8b5cf6\" strokeWidth={strokeWidth} strokeDasharray={dasharray} strokeDashoffset={offsetOB2} className=\"transition-all duration-1000 ease-out\" />"
  print "          <circle cx={center} cy={center} r={radius} fill=\"transparent\" stroke=\"#f43f5e\" strokeWidth={strokeWidth} strokeDasharray={dasharray} strokeDashoffset={offsetOB1} className=\"transition-all duration-1000 ease-out\" />"
  print "          <circle cx={center} cy={center} r={radius} fill=\"transparent\" stroke=\"#f59e0b\" strokeWidth={strokeWidth} strokeDasharray={dasharray} strokeDashoffset={offsetOW} className=\"transition-all duration-1000 ease-out\" />"
  print "          <circle cx={center} cy={center} r={radius} fill=\"transparent\" stroke=\"#10b981\" strokeWidth={strokeWidth} strokeDasharray={dasharray} strokeDashoffset={offsetN} className=\"transition-all duration-1000 ease-out\" />"
  print "          <circle cx={center} cy={center} r={radius} fill=\"transparent\" stroke=\"#3b82f6\" strokeWidth={strokeWidth} strokeDasharray={dasharray} strokeDashoffset={offsetUW} className=\"transition-all duration-1000 ease-out\" />"
  print "        </svg>"
  print "        <div className=\"absolute inset-0 flex flex-col items-center justify-center\">"
  print "          <span className=\"text-[9px] text-slate-400 font-bold uppercase tracking-wider\">ทั้งหมด</span>"
  print "          <span className=\"text-2xl font-black text-slate-800 leading-none\">{total}</span>"
  print "        </div>"
  print "      </div>"
  print "      <div className=\"w-full space-y-1.5 mt-3\">"
  print "        <div className=\"flex justify-between items-center text-[10px]\">"
  print "          <div className=\"flex items-center gap-1.5 font-semibold text-slate-600\">"
  print "            <div className=\"w-2.5 h-2.5 rounded-full bg-blue-500\"></div> ผอม"
  print "          </div>"
  print "          <span className=\"font-black text-slate-800\">{underweight} <span className=\"text-slate-400 font-semibold\">({Math.round(pctUW)}%)</span></span>"
  print "        </div>"
  print "        <div className=\"flex justify-between items-center text-[10px]\">"
  print "          <div className=\"flex items-center gap-1.5 font-semibold text-slate-600\">"
  print "            <div className=\"w-2.5 h-2.5 rounded-full bg-emerald-500\"></div> ปกติ"
  print "          </div>"
  print "          <span className=\"font-black text-slate-800\">{normal} <span className=\"text-slate-400 font-semibold\">({Math.round(pctN)}%)</span></span>"
  print "        </div>"
  print "        <div className=\"flex justify-between items-center text-[10px]\">"
  print "          <div className=\"flex items-center gap-1.5 font-semibold text-slate-600\">"
  print "            <div className=\"w-2.5 h-2.5 rounded-full bg-amber-500\"></div> ท้วม"
  print "          </div>"
  print "          <span className=\"font-black text-slate-800\">{overweight} <span className=\"text-slate-400 font-semibold\">({Math.round(pctOW)}%)</span></span>"
  print "        </div>"
  print "        <div className=\"flex justify-between items-center text-[10px]\">"
  print "          <div className=\"flex items-center gap-1.5 font-semibold text-slate-600\">"
  print "            <div className=\"w-2.5 h-2.5 rounded-full bg-rose-500\"></div> อ้วน"
  print "          </div>"
  print "          <span className=\"font-black text-slate-800\">{obese1} <span className=\"text-slate-400 font-semibold\">({Math.round(pctOB1)}%)</span></span>"
  print "        </div>"
  print "        <div className=\"flex justify-between items-center text-[10px]\">"
  print "          <div className=\"flex items-center gap-1.5 font-semibold text-slate-600\">"
  print "            <div className=\"w-2.5 h-2.5 rounded-full bg-purple-500\"></div> อ้วนมาก"
  print "          </div>"
  print "          <span className=\"font-black text-slate-800\">{obese2} <span className=\"text-slate-400 font-semibold\">({Math.round(pctOB2)}%)</span></span>"
  print "        </div>"
  print "      </div>"
  print "    </div>"
  print "  );"
  print "};"
  print ""
  print $0
  next
}
1
' src/components/NcdDashboard.tsx > src/components/NcdDashboard.tsx.tmp && mv src/components/NcdDashboard.tsx.tmp src/components/NcdDashboard.tsx
