const fs = require('fs');
const path = require('path');

const recordsPath = path.join(__dirname, 'records.json');
let existing = [];
try {
  if (fs.existsSync(recordsPath)) {
    existing = JSON.parse(fs.readFileSync(recordsPath, 'utf8'));
  }
} catch (e) {
  console.error("Error loading existing:", e);
}

const existingIds = new Set(existing.map(r => Number(r.id)));

const newRecords = [
  // 1. อำเภอเมืองสตูล
  {
    id: 1719810008001,
    date: "12/06/2567",
    visitNumber: 1,
    name: "นายฮาซัน ปูยู",
    age: 49,
    gender: "ชาย",
    address: "88 ม.1 ต.ปูยู อ.เมือง จ.สตูล",
    district: "เมือง",
    subdistrict: "ปูยู",
    targetArea: "บ้านเกาะยาว",
    modelType: "หมู่บ้าน",
    phone: "089-876-5432",
    familyHistory: ["ความดันโลหิตสูง"],
    smoking: "ไม่สูบ",
    alcohol: "ไม่ดื่มเลย",
    water: "6-8 แก้ว",
    exercise: "3 วันขึ้นไป/สัปดาห์",
    sleep: "6-8 ชั่วโมง",
    sodium: "ไม่ค่อยทานเค็ม",
    weight: 65,
    height: 168,
    bpSys: 124,
    bpDia: 80,
    sugar: 102,
    bmi: "23.03",
    followUpAction: "ให้คำแนะนำ 3อ. 2ส.",
    followUpNote: "สุขภาพทั่วไปดี แนะนำคงพฤติกรรมนี้ต่อไป",
    htResult: { level: "normal", label: "ปกติ", color: "text-emerald-700", class: "bg-emerald-100 text-emerald-800" },
    dmResult: { level: "risk", label: "กลุ่มเสี่ยง", color: "text-amber-700", class: "bg-amber-100 text-amber-800" },
    foodHabit: {
      sweet: { score: 7, level: "เสี่ยงน้อย", color: "text-emerald-600", class: "bg-emerald-50", description: "" },
      fat: { score: 6, level: "เสี่ยงน้อย", color: "text-emerald-600", class: "bg-emerald-50", description: "" },
      salt: { score: 6, level: "เสี่ยงน้อย", color: "text-emerald-600", class: "bg-emerald-50", description: "" }
    },
    createdAt: "2024-06-12T09:00:00.000Z",
    hasConsented: true
  },
  {
    id: 1719810008002,
    date: "14/08/2567",
    visitNumber: 2,
    name: "นายฮาซัน ปูยู",
    age: 49,
    gender: "ชาย",
    address: "88 ม.1 ต.ปูยู อ.เมือง จ.สตูล",
    district: "เมือง",
    subdistrict: "ปูยู",
    targetArea: "บ้านเกาะยาว",
    modelType: "หมู่บ้าน",
    phone: "089-876-5432",
    familyHistory: ["ความดันโลหิตสูง"],
    smoking: "ไม่สูบ",
    alcohol: "ไม่ดื่มเลย",
    water: "6-8 แก้ว",
    exercise: "3 วันขึ้นไป/สัปดาห์",
    sleep: "6-8 ชั่วโมง",
    sodium: "ไม่ค่อยทานเค็ม",
    weight: 64,
    height: 168,
    bpSys: 120,
    bpDia: 78,
    sugar: 96,
    bmi: "22.68",
    followUpAction: "ให้คำแนะนำ 3อ. 2ส.",
    followUpNote: "น้ำตาลกลับสู่เกณฑ์ปกติ พฤติกรรมดีมาก",
    htResult: { level: "normal", label: "ปกติ", color: "text-emerald-700", class: "bg-emerald-100 text-emerald-800" },
    dmResult: { level: "normal", label: "ปกติ", color: "text-emerald-700", class: "bg-emerald-100 text-emerald-800" },
    foodHabit: {
      sweet: { score: 5, level: "เสี่ยงน้อย", color: "text-emerald-600", class: "bg-emerald-50", description: "" },
      fat: { score: 5, level: "เสี่ยงน้อย", color: "text-emerald-600", class: "bg-emerald-50", description: "" },
      salt: { score: 5, level: "เสี่ยงน้อย", color: "text-emerald-600", class: "bg-emerald-50", description: "" }
    },
    createdAt: "2024-08-14T09:30:00.000Z",
    hasConsented: true
  },
  {
    id: 1719810009001,
    date: "15/06/2567",
    visitNumber: 1,
    name: "นางฟารีดา ตำมะลัง",
    age: 52,
    gender: "หญิง",
    address: "24 ม.2 ต.ตำมะลัง อ.เมือง จ.สตูล",
    district: "เมือง",
    subdistrict: "ตำมะลัง",
    targetArea: "บ้านตำมะลัง",
    modelType: "ตำบล",
    phone: "081-567-8901",
    familyHistory: ["เบาหวาน"],
    smoking: "ไม่สูบ",
    alcohol: "ไม่ดื่มเลย",
    water: "6-8 แก้ว",
    exercise: "1-2 วัน/สัปดาห์",
    sleep: "6-8 ชั่วโมง",
    sodium: "ทานเค็มปานกลาง",
    weight: 60,
    height: 155,
    bpSys: 132,
    bpDia: 85,
    sugar: 114,
    bmi: "24.97",
    followUpAction: "ให้คำแนะนำ 3อ. 2ส.",
    followUpNote: "แนะนำลดอาหารหวานและมัน ออกกำลังกายเพิ่มขึ้น",
    htResult: { level: "risk", label: "กลุ่มเสี่ยง", color: "text-amber-700", class: "bg-amber-100 text-amber-800" },
    dmResult: { level: "risk", label: "กลุ่มเสี่ยง", color: "text-amber-700", class: "bg-amber-100 text-amber-800" },
    foodHabit: {
      sweet: { score: 8, level: "เสี่ยงปานกลาง", color: "text-amber-600", class: "bg-amber-50", description: "" },
      fat: { score: 8, level: "เสี่ยงปานกลาง", color: "text-amber-600", class: "bg-amber-50", description: "" },
      salt: { score: 7, level: "เสี่ยงน้อย", color: "text-emerald-600", class: "bg-emerald-50", description: "" }
    },
    createdAt: "2024-06-15T10:00:00.000Z",
    hasConsented: true
  },
  {
    id: 1719810010001,
    date: "16/06/2567",
    visitNumber: 1,
    name: "นายสมเกียรติ ฉลุงสุข",
    age: 58,
    gender: "ชาย",
    address: "105 ม.1 ต.ฉลุง อ.เมือง จ.สตูล",
    district: "เมือง",
    subdistrict: "ฉลุง",
    targetArea: "ม.1 บ้านฉลุง",
    modelType: "หมู่บ้าน",
    phone: "082-345-6789",
    familyHistory: ["ความดันโลหิตสูง", "เบาหวาน"],
    smoking: "สูบเป็นประจำ",
    alcohol: "ไม่ดื่มเลย",
    water: "6-8 แก้ว",
    exercise: "ไม่ออกกำลังกาย",
    sleep: "น้อยกว่า 6 ชั่วโมง",
    sodium: "ชอบทานเค็ม",
    weight: 78,
    height: 167,
    bpSys: 148,
    bpDia: 96,
    sugar: 138,
    bmi: "27.97",
    followUpAction: "ส่งต่อพบแพทย์ รพ.สต.",
    followUpNote: "ความดันและน้ำตาลเกินเกณฑ์ ส่งต่อพบแพทย์ รพ.สต.ฉลุง",
    htResult: { level: "danger", label: "สงสัยป่วย", color: "text-rose-700", class: "bg-rose-100 text-rose-800" },
    dmResult: { level: "danger", label: "สงสัยป่วย", color: "text-rose-700", class: "bg-rose-100 text-rose-800" },
    foodHabit: {
      sweet: { score: 11, level: "เสี่ยงสูง", color: "text-rose-600", class: "bg-rose-50", description: "" },
      fat: { score: 12, level: "เสี่ยงสูงมาก", color: "text-rose-700", class: "bg-rose-100", description: "" },
      salt: { score: 13, level: "เสี่ยงสูงมาก", color: "text-rose-700", class: "bg-rose-100", description: "" }
    },
    createdAt: "2024-06-16T11:00:00.000Z",
    hasConsented: true
  },
  {
    id: 1719810011001,
    date: "17/06/2567",
    visitNumber: 1,
    name: "นางวรรณี บ้านควน",
    age: 46,
    gender: "หญิง",
    address: "52 ม.2 ต.บ้านควน อ.เมือง จ.สตูล",
    district: "เมือง",
    subdistrict: "บ้านควน",
    targetArea: "ม.2 บ้านกุบังจามัง",
    modelType: "ตำบล",
    phone: "083-456-7890",
    familyHistory: [],
    smoking: "ไม่สูบ",
    alcohol: "ไม่ดื่มเลย",
    water: "มากกว่า 8 แก้ว",
    exercise: "3 วันขึ้นไป/สัปดาห์",
    sleep: "6-8 ชั่วโมง",
    sodium: "ไม่ค่อยทานเค็ม",
    weight: 54,
    height: 158,
    bpSys: 116,
    bpDia: 76,
    sugar: 90,
    bmi: "21.63",
    followUpAction: "ให้คำแนะนำ 3อ. 2ส.",
    followUpNote: "สุขภาพสมบูรณ์แข็งแรงดี",
    htResult: { level: "normal", label: "ปกติ", color: "text-emerald-700", class: "bg-emerald-100 text-emerald-800" },
    dmResult: { level: "normal", label: "ปกติ", color: "text-emerald-700", class: "bg-emerald-100 text-emerald-800" },
    foodHabit: {
      sweet: { score: 4, level: "เสี่ยงน้อย", color: "text-emerald-600", class: "bg-emerald-50", description: "" },
      fat: { score: 5, level: "เสี่ยงน้อย", color: "text-emerald-600", class: "bg-emerald-50", description: "" },
      salt: { score: 4, level: "เสี่ยงน้อย", color: "text-emerald-600", class: "bg-emerald-50", description: "" }
    },
    createdAt: "2024-06-17T09:15:00.000Z",
    hasConsented: true
  },

  // 2. อำเภอละงู
  {
    id: 1719810012001,
    date: "18/06/2567",
    visitNumber: 1,
    name: "นายเกษม ปากบารา",
    age: 55,
    gender: "ชาย",
    address: "71 ม.2 ต.ปากน้ำ อ.ละงู จ.สตูล",
    district: "ละงู",
    subdistrict: "ปากน้ำ",
    targetArea: "ม.2 บ้านปากบารา",
    modelType: "หมู่บ้าน",
    phone: "084-567-8901",
    familyHistory: ["ความดันโลหิตสูง"],
    smoking: "สูบเป็นครั้งคราว",
    alcohol: "ดื่มครั้งคราว",
    water: "6-8 แก้ว",
    exercise: "1-2 วัน/สัปดาห์",
    sleep: "6-8 ชั่วโมง",
    sodium: "ทานเค็มปานกลาง",
    weight: 70,
    height: 165,
    bpSys: 135,
    bpDia: 88,
    sugar: 108,
    bmi: "25.71",
    followUpAction: "ให้คำแนะนำ 3อ. 2ส.",
    followUpNote: "แนะนำงดบุหรี่และสุรา ควบคุมน้ำหนัก",
    htResult: { level: "risk", label: "กลุ่มเสี่ยง", color: "text-amber-700", class: "bg-amber-100 text-amber-800" },
    dmResult: { level: "risk", label: "กลุ่มเสี่ยง", color: "text-amber-700", class: "bg-amber-100 text-amber-800" },
    foodHabit: {
      sweet: { score: 7, level: "เสี่ยงน้อย", color: "text-emerald-600", class: "bg-emerald-50", description: "" },
      fat: { score: 9, level: "เสี่ยงปานกลาง", color: "text-amber-600", class: "bg-amber-50", description: "" },
      salt: { score: 8, level: "เสี่ยงปานกลาง", color: "text-amber-600", class: "bg-amber-50", description: "" }
    },
    createdAt: "2024-06-18T10:30:00.000Z",
    hasConsented: true
  },
  {
    id: 1719810013001,
    date: "19/06/2567",
    visitNumber: 1,
    name: "นางสีตี บ่อหิน",
    age: 61,
    gender: "หญิง",
    address: "39 ม.1 ต.ละงู อ.ละงู จ.สตูล",
    district: "ละงู",
    subdistrict: "ละงู",
    targetArea: "ม.1 บ้านบ่อหิน",
    modelType: "ตำบล",
    phone: "085-678-9012",
    familyHistory: ["เบาหวาน"],
    smoking: "ไม่สูบ",
    alcohol: "ไม่ดื่มเลย",
    water: "6-8 แก้ว",
    exercise: "3 วันขึ้นไป/สัปดาห์",
    sleep: "6-8 ชั่วโมง",
    sodium: "ไม่ค่อยทานเค็ม",
    weight: 58,
    height: 154,
    bpSys: 122,
    bpDia: 80,
    sugar: 105,
    bmi: "24.46",
    followUpAction: "ให้คำแนะนำ 3อ. 2ส.",
    followUpNote: "ปฏิบัติตัวดี แนะนำลดขนมหวานพื้นบ้าน",
    htResult: { level: "normal", label: "ปกติ", color: "text-emerald-700", class: "bg-emerald-100 text-emerald-800" },
    dmResult: { level: "risk", label: "กลุ่มเสี่ยง", color: "text-amber-700", class: "bg-amber-100 text-amber-800" },
    foodHabit: {
      sweet: { score: 8, level: "เสี่ยงปานกลาง", color: "text-amber-600", class: "bg-amber-50", description: "" },
      fat: { score: 6, level: "เสี่ยงน้อย", color: "text-emerald-600", class: "bg-emerald-50", description: "" },
      salt: { score: 5, level: "เสี่ยงน้อย", color: "text-emerald-600", class: "bg-emerald-50", description: "" }
    },
    createdAt: "2024-06-19T08:45:00.000Z",
    hasConsented: true
  },

  // 3. อำเภอท่าแพ
  {
    id: 1719810014001,
    date: "20/06/2567",
    visitNumber: 1,
    name: "นายมะนอ แป-ระ",
    age: 50,
    gender: "ชาย",
    address: "18 ม.1 ต.แป-ระ อ.ท่าแพ จ.สตูล",
    district: "ท่าแพ",
    subdistrict: "แป-ระ",
    targetArea: "ม.1 บ้านแป-ระ",
    modelType: "หมู่บ้าน",
    phone: "086-789-0123",
    familyHistory: ["ความดันโลหิตสูง"],
    smoking: "ไม่สูบ",
    alcohol: "ไม่ดื่มเลย",
    water: "6-8 แก้ว",
    exercise: "3 วันขึ้นไป/สัปดาห์",
    sleep: "6-8 ชั่วโมง",
    sodium: "ทานเค็มปานกลาง",
    weight: 63,
    height: 165,
    bpSys: 126,
    bpDia: 82,
    sugar: 98,
    bmi: "23.14",
    followUpAction: "ให้คำแนะนำ 3อ. 2ส.",
    followUpNote: "สุขภาพดี แนะนำลดเค็มในแกงส้ม",
    htResult: { level: "risk", label: "กลุ่มเสี่ยง", color: "text-amber-700", class: "bg-amber-100 text-amber-800" },
    dmResult: { level: "normal", label: "ปกติ", color: "text-emerald-700", class: "bg-emerald-100 text-emerald-800" },
    foodHabit: {
      sweet: { score: 5, level: "เสี่ยงน้อย", color: "text-emerald-600", class: "bg-emerald-50", description: "" },
      fat: { score: 6, level: "เสี่ยงน้อย", color: "text-emerald-600", class: "bg-emerald-50", description: "" },
      salt: { score: 8, level: "เสี่ยงปานกลาง", color: "text-amber-600", class: "bg-amber-50", description: "" }
    },
    createdAt: "2024-06-20T09:30:00.000Z",
    hasConsented: true
  },
  {
    id: 1719810015001,
    date: "21/06/2567",
    visitNumber: 1,
    name: "นางมณี สาครดี",
    age: 57,
    gender: "หญิง",
    address: "65 ม.1 ต.สาคร อ.ท่าแพ จ.สตูล",
    district: "ท่าแพ",
    subdistrict: "สาคร",
    targetArea: "ม.1 บ้านสาคร",
    modelType: "ตำบล",
    phone: "087-890-1234",
    familyHistory: ["ความดันโลหิตสูง", "หลอดเลือดสมอง"],
    smoking: "ไม่สูบ",
    alcohol: "ไม่ดื่มเลย",
    water: "6-8 แก้ว",
    exercise: "ไม่ออกกำลังกาย",
    sleep: "น้อยกว่า 6 ชั่วโมง",
    sodium: "ชอบทานเค็ม",
    weight: 69,
    height: 153,
    bpSys: 144,
    bpDia: 92,
    sugar: 126,
    bmi: "29.48",
    followUpAction: "ส่งต่อพบแพทย์ รพ.สต.",
    followUpNote: "ความดันสูง น้ำหนักเกิน ส่งต่อตรวจยืนยันความดัน",
    htResult: { level: "danger", label: "สงสัยป่วย", color: "text-rose-700", class: "bg-rose-100 text-rose-800" },
    dmResult: { level: "risk", label: "กลุ่มเสี่ยง", color: "text-amber-700", class: "bg-amber-100 text-amber-800" },
    foodHabit: {
      sweet: { score: 9, level: "เสี่ยงปานกลาง", color: "text-amber-600", class: "bg-amber-50", description: "" },
      fat: { score: 11, level: "เสี่ยงสูง", color: "text-rose-600", class: "bg-rose-50", description: "" },
      salt: { score: 12, level: "เสี่ยงสูงมาก", color: "text-rose-700", class: "bg-rose-100", description: "" }
    },
    createdAt: "2024-06-21T10:15:00.000Z",
    hasConsented: true
  },

  // 4. อำเภอควนโดน
  {
    id: 1719810016001,
    date: "22/06/2567",
    visitNumber: 1,
    name: "นายดนัย ควนสตอ",
    age: 48,
    gender: "ชาย",
    address: "33 ม.1 ต.ควนสตอ อ.ควนโดน จ.สตูล",
    district: "ควนโดน",
    subdistrict: "ควนสตอ",
    targetArea: "บ้านควนสตอ (ต.ควนสตอ)",
    modelType: "หมู่บ้าน",
    phone: "088-901-2345",
    familyHistory: [],
    smoking: "ไม่สูบ",
    alcohol: "ไม่ดื่มเลย",
    water: "6-8 แก้ว",
    exercise: "3 วันขึ้นไป/สัปดาห์",
    sleep: "6-8 ชั่วโมง",
    sodium: "ไม่ค่อยทานเค็ม",
    weight: 62,
    height: 167,
    bpSys: 118,
    bpDia: 78,
    sugar: 94,
    bmi: "22.23",
    followUpAction: "ให้คำแนะนำ 3อ. 2ส.",
    followUpNote: "สุขภาพร่างกายแข็งแรงดีมาก",
    htResult: { level: "normal", label: "ปกติ", color: "text-emerald-700", class: "bg-emerald-100 text-emerald-800" },
    dmResult: { level: "normal", label: "ปกติ", color: "text-emerald-700", class: "bg-emerald-100 text-emerald-800" },
    foodHabit: {
      sweet: { score: 4, level: "เสี่ยงน้อย", color: "text-emerald-600", class: "bg-emerald-50", description: "" },
      fat: { score: 5, level: "เสี่ยงน้อย", color: "text-emerald-600", class: "bg-emerald-50", description: "" },
      salt: { score: 5, level: "เสี่ยงน้อย", color: "text-emerald-600", class: "bg-emerald-50", description: "" }
    },
    createdAt: "2024-06-22T09:00:00.000Z",
    hasConsented: true
  },
  {
    id: 1719810017001,
    date: "23/06/2567",
    visitNumber: 1,
    name: "นางไซหนับ ย่านซื่อ",
    age: 53,
    gender: "หญิง",
    address: "77 ม.1 ต.ย่านซื่อ อ.ควนโดน จ.สตูล",
    district: "ควนโดน",
    subdistrict: "ย่านซื่อ",
    targetArea: "บ้านย่านซื่อ (ต.ย่านซื่อ)",
    modelType: "ตำบล",
    phone: "089-012-3456",
    familyHistory: ["ความดันโลหิตสูง"],
    smoking: "ไม่สูบ",
    alcohol: "ไม่ดื่มเลย",
    water: "6-8 แก้ว",
    exercise: "1-2 วัน/สัปดาห์",
    sleep: "6-8 ชั่วโมง",
    sodium: "ทานเค็มปานกลาง",
    weight: 64,
    height: 156,
    bpSys: 130,
    bpDia: 84,
    sugar: 104,
    bmi: "26.30",
    followUpAction: "ให้คำแนะนำ 3อ. 2ส.",
    followUpNote: "กลุ่มเสี่ยงความดันโลหิตสูง แนะนำลดโซเดียมและเดินเร็ว",
    htResult: { level: "risk", label: "กลุ่มเสี่ยง", color: "text-amber-700", class: "bg-amber-100 text-amber-800" },
    dmResult: { level: "normal", label: "ปกติ", color: "text-emerald-700", class: "bg-emerald-100 text-emerald-800" },
    foodHabit: {
      sweet: { score: 6, level: "เสี่ยงน้อย", color: "text-emerald-600", class: "bg-emerald-50", description: "" },
      fat: { score: 7, level: "เสี่ยงน้อย", color: "text-emerald-600", class: "bg-emerald-50", description: "" },
      salt: { score: 9, level: "เสี่ยงปานกลาง", color: "text-amber-600", class: "bg-amber-50", description: "" }
    },
    createdAt: "2024-06-23T10:45:00.000Z",
    hasConsented: true
  },

  // 5. อำเภอควนกาหลง
  {
    id: 1719810018001,
    date: "24/06/2567",
    visitNumber: 1,
    name: "นายสุนทร ทุ่งนุ้ย",
    age: 56,
    gender: "ชาย",
    address: "92 ม.1 ต.ทุ่งนุ้ย อ.ควนกาหลง จ.สตูล",
    district: "ควนกาหลง",
    subdistrict: "ทุ่งนุ้ย",
    targetArea: "ม.1 บ้านทุ่งนุ้ย",
    modelType: "หมู่บ้าน",
    phone: "080-123-4567",
    familyHistory: ["เบาหวาน"],
    smoking: "สูบเป็นประจำ",
    alcohol: "ไม่ดื่มเลย",
    water: "6-8 แก้ว",
    exercise: "1-2 วัน/สัปดาห์",
    sleep: "6-8 ชั่วโมง",
    sodium: "ทานเค็มปานกลาง",
    weight: 71,
    height: 168,
    bpSys: 136,
    bpDia: 88,
    sugar: 122,
    bmi: "25.16",
    followUpAction: "ให้คำแนะนำ 3อ. 2ส.",
    followUpNote: "เสี่ยงเบาหวานและความดัน แนะนำเลิกบุหรี่",
    htResult: { level: "risk", label: "กลุ่มเสี่ยง", color: "text-amber-700", class: "bg-amber-100 text-amber-800" },
    dmResult: { level: "risk", label: "กลุ่มเสี่ยง", color: "text-amber-700", class: "bg-amber-100 text-amber-800" },
    foodHabit: {
      sweet: { score: 10, level: "เสี่ยงสูง", color: "text-rose-600", class: "bg-rose-50", description: "" },
      fat: { score: 8, level: "เสี่ยงปานกลาง", color: "text-amber-600", class: "bg-amber-50", description: "" },
      salt: { score: 8, level: "เสี่ยงปานกลาง", color: "text-amber-600", class: "bg-amber-50", description: "" }
    },
    createdAt: "2024-06-24T09:30:00.000Z",
    hasConsented: true
  },
  {
    id: 1719810018002,
    date: "28/08/2567",
    visitNumber: 2,
    name: "นายสุนทร ทุ่งนุ้ย",
    age: 56,
    gender: "ชาย",
    address: "92 ม.1 ต.ทุ่งนุ้ย อ.ควนกาหลง จ.สตูล",
    district: "ควนกาหลง",
    subdistrict: "ทุ่งนุ้ย",
    targetArea: "ม.1 บ้านทุ่งนุ้ย",
    modelType: "หมู่บ้าน",
    phone: "080-123-4567",
    familyHistory: ["เบาหวาน"],
    smoking: "สูบเป็นครั้งคราว",
    alcohol: "ไม่ดื่มเลย",
    water: "6-8 แก้ว",
    exercise: "3 วันขึ้นไป/สัปดาห์",
    sleep: "6-8 ชั่วโมง",
    sodium: "ไม่ค่อยทานเค็ม",
    weight: 69,
    height: 168,
    bpSys: 126,
    bpDia: 82,
    sugar: 106,
    bmi: "24.45",
    followUpAction: "ให้คำแนะนำ 3อ. 2ส.",
    followUpNote: "ลดบุหรี่ลงได้มาก น้ำตาลและความดันลดลงต่อเนื่อง",
    htResult: { level: "normal", label: "ปกติ", color: "text-emerald-700", class: "bg-emerald-100 text-emerald-800" },
    dmResult: { level: "risk", label: "กลุ่มเสี่ยง", color: "text-amber-700", class: "bg-amber-100 text-amber-800" },
    foodHabit: {
      sweet: { score: 7, level: "เสี่ยงน้อย", color: "text-emerald-600", class: "bg-emerald-50", description: "" },
      fat: { score: 6, level: "เสี่ยงน้อย", color: "text-emerald-600", class: "bg-emerald-50", description: "" },
      salt: { score: 6, level: "เสี่ยงน้อย", color: "text-emerald-600", class: "bg-emerald-50", description: "" }
    },
    createdAt: "2024-08-28T10:00:00.000Z",
    hasConsented: true
  },

  // 6. อำเภอทุ่งหว้า
  {
    id: 1719810019001,
    date: "25/06/2567",
    visitNumber: 1,
    name: "นายประเสริฐ นาทอน",
    age: 51,
    gender: "ชาย",
    address: "41 ม.1 ต.นาทอน อ.ทุ่งหว้า จ.สตูล",
    district: "ทุ่งหว้า",
    subdistrict: "นาทอน",
    targetArea: "ม.1 บ้านนาทอน",
    modelType: "หมู่บ้าน",
    phone: "081-234-5670",
    familyHistory: ["ความดันโลหิตสูง"],
    smoking: "ไม่สูบ",
    alcohol: "ไม่ดื่มเลย",
    water: "6-8 แก้ว",
    exercise: "3 วันขึ้นไป/สัปดาห์",
    sleep: "6-8 ชั่วโมง",
    sodium: "ไม่ค่อยทานเค็ม",
    weight: 66,
    height: 169,
    bpSys: 122,
    bpDia: 80,
    sugar: 96,
    bmi: "23.11",
    followUpAction: "ให้คำแนะนำ 3อ. 2ส.",
    followUpNote: "สุขภาพร่างกายปกติ แนะนำรักษาระดับนี้ไว้",
    htResult: { level: "normal", label: "ปกติ", color: "text-emerald-700", class: "bg-emerald-100 text-emerald-800" },
    dmResult: { level: "normal", label: "ปกติ", color: "text-emerald-700", class: "bg-emerald-100 text-emerald-800" },
    foodHabit: {
      sweet: { score: 5, level: "เสี่ยงน้อย", color: "text-emerald-600", class: "bg-emerald-50", description: "" },
      fat: { score: 5, level: "เสี่ยงน้อย", color: "text-emerald-600", class: "bg-emerald-50", description: "" },
      salt: { score: 5, level: "เสี่ยงน้อย", color: "text-emerald-600", class: "bg-emerald-50", description: "" }
    },
    createdAt: "2024-06-25T11:00:00.000Z",
    hasConsented: true
  },
  {
    id: 1719810020001,
    date: "26/06/2567",
    visitNumber: 1,
    name: "นางพรทิพย์ ทุ่งบุหลัง",
    age: 59,
    gender: "หญิง",
    address: "83 ม.1 ต.ทุ่งบุหลัง อ.ทุ่งหว้า จ.สตูล",
    district: "ทุ่งหว้า",
    subdistrict: "ทุ่งบุหลัง",
    targetArea: "ม.1 บ้านทุ่งบุหลัง",
    modelType: "ตำบล",
    phone: "082-345-6701",
    familyHistory: ["เบาหวาน", "ไขมันในเลือดสูง"],
    smoking: "ไม่สูบ",
    alcohol: "ไม่ดื่มเลย",
    water: "6-8 แก้ว",
    exercise: "ไม่ออกกำลังกาย",
    sleep: "น้อยกว่า 6 ชั่วโมง",
    sodium: "ทานเค็มปานกลาง",
    weight: 65,
    height: 152,
    bpSys: 140,
    bpDia: 90,
    sugar: 130,
    bmi: "28.13",
    followUpAction: "ส่งต่อพบแพทย์ รพ.สต.",
    followUpNote: "ความดันและน้ำตาลสูง ส่งต่อพบแพทย์ รพ.สต.ทุ่งบุหลัง",
    htResult: { level: "danger", label: "สงสัยป่วย", color: "text-rose-700", class: "bg-rose-100 text-rose-800" },
    dmResult: { level: "danger", label: "สงสัยป่วย", color: "text-rose-700", class: "bg-rose-100 text-rose-800" },
    foodHabit: {
      sweet: { score: 11, level: "เสี่ยงสูง", color: "text-rose-600", class: "bg-rose-50", description: "" },
      fat: { score: 10, level: "เสี่ยงสูง", color: "text-rose-600", class: "bg-rose-50", description: "" },
      salt: { score: 9, level: "เสี่ยงปานกลาง", color: "text-amber-600", class: "bg-amber-50", description: "" }
    },
    createdAt: "2024-06-26T09:15:00.000Z",
    hasConsented: true
  },

  // 7. อำเภอมะนัง
  {
    id: 1719810021001,
    date: "27/06/2567",
    visitNumber: 1,
    name: "นายชูศักดิ์ ปาล์มพัฒนา",
    age: 47,
    gender: "ชาย",
    address: "16 ม.8 ต.ปาล์มพัฒนา อ.มะนัง จ.สตูล",
    district: "มะนัง",
    subdistrict: "ปาล์มพัฒนา",
    targetArea: "ม.8 บ้านปาล์มทองพัฒนา",
    modelType: "หมู่บ้าน",
    phone: "083-456-7012",
    familyHistory: ["ความดันโลหิตสูง"],
    smoking: "ไม่สูบ",
    alcohol: "ไม่ดื่มเลย",
    water: "มากกว่า 8 แก้ว",
    exercise: "3 วันขึ้นไป/สัปดาห์",
    sleep: "6-8 ชั่วโมง",
    sodium: "ไม่ค่อยทานเค็ม",
    weight: 65,
    height: 170,
    bpSys: 120,
    bpDia: 78,
    sugar: 92,
    bmi: "22.49",
    followUpAction: "ให้คำแนะนำ 3อ. 2ส.",
    followUpNote: "สุขภาพร่างกายแข็งแรงดีมาก",
    htResult: { level: "normal", label: "ปกติ", color: "text-emerald-700", class: "bg-emerald-100 text-emerald-800" },
    dmResult: { level: "normal", label: "ปกติ", color: "text-emerald-700", class: "bg-emerald-100 text-emerald-800" },
    foodHabit: {
      sweet: { score: 4, level: "เสี่ยงน้อย", color: "text-emerald-600", class: "bg-emerald-50", description: "" },
      fat: { score: 4, level: "เสี่ยงน้อย", color: "text-emerald-600", class: "bg-emerald-50", description: "" },
      salt: { score: 4, level: "เสี่ยงน้อย", color: "text-emerald-600", class: "bg-emerald-50", description: "" }
    },
    createdAt: "2024-06-27T10:00:00.000Z",
    hasConsented: true
  },
  {
    id: 1719810022001,
    date: "28/06/2567",
    visitNumber: 1,
    name: "นางละออง นิคมพัฒนา",
    age: 54,
    gender: "หญิง",
    address: "95 ม.4 ต.นิคมพัฒนา อ.มะนัง จ.สตูล",
    district: "มะนัง",
    subdistrict: "นิคมพัฒนา",
    targetArea: "ม.4 บ้านผัง 8,11,12",
    modelType: "ตำบล",
    phone: "084-567-0123",
    familyHistory: ["เบาหวาน"],
    smoking: "ไม่สูบ",
    alcohol: "ไม่ดื่มเลย",
    water: "6-8 แก้ว",
    exercise: "1-2 วัน/สัปดาห์",
    sleep: "6-8 ชั่วโมง",
    sodium: "ทานเค็มปานกลาง",
    weight: 61,
    height: 155,
    bpSys: 128,
    bpDia: 82,
    sugar: 112,
    bmi: "25.39",
    followUpAction: "ให้คำแนะนำ 3อ. 2ส.",
    followUpNote: "กลุ่มเสี่ยงเบาหวานและความดัน แนะนำคุมอาหารหวานมัน",
    htResult: { level: "risk", label: "กลุ่มเสี่ยง", color: "text-amber-700", class: "bg-amber-100 text-amber-800" },
    dmResult: { level: "risk", label: "กลุ่มเสี่ยง", color: "text-amber-700", class: "bg-amber-100 text-amber-800" },
    foodHabit: {
      sweet: { score: 8, level: "เสี่ยงปานกลาง", color: "text-amber-600", class: "bg-amber-50", description: "" },
      fat: { score: 8, level: "เสี่ยงปานกลาง", color: "text-amber-600", class: "bg-amber-50", description: "" },
      salt: { score: 7, level: "เสี่ยงน้อย", color: "text-emerald-600", class: "bg-emerald-50", description: "" }
    },
    createdAt: "2024-06-28T09:30:00.000Z",
    hasConsented: true
  }
];

// Merge unique
const merged = [...existing];
newRecords.forEach(nr => {
  if (!existingIds.has(nr.id)) {
    merged.push(nr);
    existingIds.add(nr.id);
  }
});

merged.sort((a, b) => (Number(b.id) || 0) - (Number(a.id) || 0));

fs.writeFileSync(recordsPath, JSON.stringify(merged, null, 2), 'utf8');
console.log(`Seeded complete records. Total now: ${merged.length}`);
